/****************************************************************************
 * apps/games/NXDoom/src/doom/p_pspr.h
 *
 * SPDX-License-Identifer: GPLv2
 *
 * Copyright(C) 1993-1996 Id Software, Inc.
 * Copyright(C) 2005-2014 Simon Howard
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * DESCRIPTION:
 *   Sprite animation.
 *
 ****************************************************************************/

#ifndef __P_PSPR__
#define __P_PSPR__

/****************************************************************************
 * Included Files
 ****************************************************************************/

/* Basic data types.
 * Needs fixed point, and BAM angles.
 */

#include "m_fixed.h"
#include "tables.h"

/* Needs to include the precompiled sprite animation tables.
 *
 * Header generated by multigen utility.
 *
 * This includes all the data for thing animation,
 * i.e. the Thing Attributes table and the Frame Sequence table.
 */

#include "info.h"

/* Frame flags:
 * handles maximum brightness (torches, muzzle flare, light sources)
 */

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

#define FF_FULLBRIGHT 0x8000 /* flag in thing->frame */
#define FF_FRAMEMASK 0x7fff

/****************************************************************************
 * Public Types
 ****************************************************************************/

/* Overlay psprites are scaled shapes drawn directly on the view screen,
 * coordinates are given for a 320*200 view screen.
 */

typedef enum
{
  ps_weapon,
  ps_flash,
  NUMPSPRITES
} psprnum_t;

typedef struct
{
  state_t *state; /* a NULL state means not active */
  int tics;
  fixed_t sx;
  fixed_t sy;
} pspdef_t;

/****************************************************************************
 * Public Data
 ****************************************************************************/

extern fixed_t bulletslope;

#endif /* __P_PSPR__ */
