############################################################################
# apps/netutils/libcurl4nx/Makefile
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.  The
# ASF licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
############################################################################

include $(APPDIR)/Make.defs

# Web client library

CSRCS = curl4nx_easy_init.c curl4nx_easy_cleanup.c \
        curl4nx_easy_reset.c curl4nx_easy_duphandle.c \
        curl4nx_easy_escape.c curl4nx_easy_unescape.c \
        curl4nx_easy_setopt.c curl4nx_easy_perform.c \
        curl4nx_easy_getinfo.c

include $(APPDIR)/Application.mk
