############################################################################
# apps/testing/sig_sp_test/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_TESTING_SIG_SP_TEST_PROGNAME)
PRIORITY  = $(CONFIG_TESTING_SIG_SP_TEST_PRIORITY)
STACKSIZE = $(CONFIG_TESTING_SIG_SP_TEST_STACKSIZE)
MODULE    = $(CONFIG_TESTING_SIG_SP_TEST)

MAINSRC = sig_sp_test_main.c

include $(APPDIR)/Application.mk
