#if !defined(_TOYWASM_CONFIG_H)
#define _TOYWASM_CONFIG_H

#define TOYWASM_USE_SEPARATE_EXECUTE
#define TOYWASM_USE_TAILCALL
/* #undef TOYWASM_ENABLE_TRACING */
#define TOYWASM_USE_JUMP_BINARY_SEARCH
/* #undef TOYWASM_USE_JUMP_CACHE */
#define TOYWASM_JUMP_CACHE2_SIZE 4
#define TOYWASM_USE_LOCALS_CACHE
#define TOYWASM_USE_SEPARATE_LOCALS
#define TOYWASM_USE_SMALL_CELLS
#define TOYWASM_USE_RESULTTYPE_CELLIDX
#define TOYWASM_USE_LOCALTYPE_CELLIDX
#define TOYWASM_ENABLE_WRITER

#endif /* !defined(_TOYWASM_CONFIG_H) */
