# Info about this package.
[package]
authors = ["Lee Lup Yuen <luppy@appkaki.com>"]
edition = "2018"
readme  = "README.md"
name    = "app"
version = "0.0.1"

# External Rust libraries used by this module.  See crates.io.
[dependencies]
heapless     = "0.7.5"  # `static` friendly data structures that don't require dynamic memory allocation: https://crates.io/crates/heapless

# Build this module as a Rust library, not a Rust application.  We will link this library with the BL602 firmware.
[lib]
name       = "app"  # Output will be named `libapp.a`
test       = false
bench      = false
crate-type = ["staticlib"]

# Build settings for Development Profile
[profile.dev]
opt-level = 3        # Enable all optimizations
panic     = 'abort'  # Terminate the process upon panic
# lto     = true     # Enable Link Time Optimization for smaller binaries

# Optional features
[features]
default =  [  # Select the conditional compiled features
]