# Info about this package.
[package]
authors = ["Lee Lup Yuen <luppy@appkaki.com>"]
edition = "2018"
readme  = "README.md"
name    = "app"
version = "0.0.1"

# External Rust libraries used by this module.  See crates.io.
[dependencies]
heapless     = "0.7.5"  # `static` friendly data structures that don't require dynamic memory allocation: https://crates.io/crates/heapless
embedded-hal = "0.2.3"  # Embedded HAL: https://crates.io/crates/embedded-hal
sx126x       = { git = "https://github.com/lupyuen/sx126x-rs-nuttx" }  # SX126x LoRa Radio Driver fixed for NuttX
# sx126x     = { path = "../../../../sx126x-rs-nuttx" }  # For local development

# Build this module as a Rust library, not a Rust application.  We will link this library with the BL602 firmware.
[lib]
name       = "app"  # Output will be named `libapp.a`
test       = false
bench      = false
crate-type = ["staticlib"]

# Build settings for Development Profile
[profile.dev]
opt-level = "s"      # Optimize for size
panic     = "abort"  # Terminate the process upon panic
# lto     = true     # Enable Link Time Optimization for smaller binaries

# Optional features
[features]
default =  [  # Select the conditional compiled features
]