#!/usr/bin/env sh
############################################################################
# apps/examples/fdpicxip/modules/mkblobs.sh
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.  The
# ASF licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
############################################################################

# Print the C arrays that carry FDPIC modules in an application image.
#
#   mkblobs.sh <prefix> <module>...
#
# Each module becomes <prefix>_<name>[] and <prefix>_<name>_len, where <name>
# is its file name with each character other than a letter or a digit
# changed to '_'.  A file that is not an FDPIC module stops the build.

set -e

prefix=$1
shift

for module in "$@"; do
  # An FDPIC module is ET_DYN (3) with EI_OSABI ELFOSABI_ARM_FDPIC (65)

  magic=$(od -An -c -N4 "$module" | tr -d ' ')
  osabi=$(od -An -tu1 -j7 -N1 "$module" | tr -d ' ')
  etype=$(od -An -tu1 -j16 -N2 "$module" | awk 'NF { print $1 + 256 * $2 }')

  if [ "$magic" != "177ELF" ] || [ "$osabi" != "65" ] ||
     [ "$etype" != "3" ]; then
    echo "ERROR: $module is not an FDPIC module." >&2
    echo "CONFIG_FDPIC needs a toolchain that links FDPIC modules." >&2
    exit 1
  fi
done

echo "/* Generated by mkblobs.sh.  Do not edit. */"

for module in "$@"; do
  name=${prefix}_$(basename "$module" | tr -c 'A-Za-z0-9\n' '_')

  echo
  echo "const unsigned char ${name}[] ="
  echo "{"
  xxd -i < "$module"
  echo "};"
  echo
  echo "const unsigned int ${name}_len = $(wc -c < "$module" | tr -d ' ');"
done
