#ifndef __ESP_HOSTED_CONFIG_H
#define __ESP_HOSTED_CONFIG_H
#endif

#define INPUT_OPERATING_MODE                    STATION+SOFTAP
#define INPUT_STATION__SSID                     "Your wifi name"
#define INPUT_STATION_PASSWORD                  "Your Password"
#define INPUT_STATION_BSSID
#define INPUT_STATION_IS_WPA3_SUPPORTED
#define INPUT_STATION_SRC_IP
#define INPUT_STATION_ARP_DEST_IP
#define INPUT_GET_AP_SCAN_LIST
#define INPUT_SOFTAP__SSID
#define INPUT_SOFTAP_PASSWORD
#define INPUT_SOFTAP_PASSWORD
#define INPUT_SOFTAP_CHANNEL
#define INPUT_SOFTAP_BANDWIDTH
#define INPUT_SOFTAP_BANDWIDTH
#define INPUT_SOFTAP_ENCRYPTION
#define INPUT_SOFTAP_MAX_XONN
#define INPUT_SOFTAP_SSID_HIDDEN
#define INPUT_SOFTAP_SRC_IP
#define INPUT_SOFTAP_ARP_DEST_IP